/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Bag.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Bag.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bag.geometry} material={materials.HatAndBag} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Bag.gltf')
