/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 soldier.gltf
Author: 6lucius (https://sketchfab.com/6lucius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sas-cs2-agent-model-green-125aa3eea297477aafdf12bfdb1f5dba
Title: SAS | CS2 Agent Model Green
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/soldier.gltf')
  const { actions } = useAnimations(animations, group)
  const modelHeight = 4.5; // Replace with the actual height of your model
  const verticalOffset = -modelHeight / 2;


  return (
    <group ref={group} {...props} dispose={null} position={[0, verticalOffset, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="sas_green_85" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.07}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="charactersmodelsctm_sasctm_sas_variantfvmdl_cdefault_glove_84" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['glove_hardknuckle_black.001']} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['ctm_sas_bodylegs_variantf.001']} skeleton={nodes.Object_8.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['ctm_sas_body_variantf.001']} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['ctm_sas_head_gasmask_variantf.001']} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['ctm_sas_lenses_variantf.001']} skeleton={nodes.Object_11.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/soldier.gltf')
